stock_project/chips/urls.py
from django.urls import path
from chips import views

app_name='chips'
urlpatterns=[
    path('',views.chips, name='chips'),
    path('chips2',views.chips2, name='chips2'),
    ] 

stock_project/choose/urls.py
from django.urls import path
from choose import views

app_name='choose'
urlpatterns=[
    path('',views.choose, name='choose'),
    path('timely_stock',views.timely_stock, name='timely_stock'),
    path('choose2',views.choose2, name='choose2'),
    path('choose2_submit',views.choose2_submit, name='choose2_submit'),
    #path('addrandom',views.addrandom, name='addrandom'),
    #path('random',views.random, name='random'),
    ] 

stock_project/newbie/urls.py
from django.urls import path
from newbie import views

app_name='newbie'
urlpatterns=[
    path('',views.newbie, name='newbie'),
    ] 

stock_project/predict/urls.py
from django.urls import path
from predict import views

app_name='predict'
urlpatterns=[
    path('',views.predict, name='predict'),
    path('newUrl',views.newUrl, name='newUrl'),
    path('newImg',views.newImg, name='newImg'),
    ] 

stock_project/stock/urls.py
from django.urls import path
from stock import views

app_name='stock'
urlpatterns=[
    path('',views.stock, name='stock'),
    ] 

stock_project/stock_project/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from stock import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('stock/',include('stock.urls',namespace='stock')),
    path('choose/',include('choose.urls',namespace='choose')),
    path('chips/',include('chips.urls',namespace='chips')),
    path('trend/',include('trend.urls',namespace='trend')),
    path('newbie/',include('newbie.urls',namespace='newbie')),
    path('transaction/',include('transaction.urls',namespace='transaction')),
    path('predict/',include('predict.urls',namespace='predict')),
    re_path('.*',views.stock),
    ]

stock_project/trend/urls.py
from django.urls import path
from trend import views

app_name='trend'
urlpatterns=[
    path('',views.trend, name='trend'),
    # path('trend_stock',views.trend_stock, name='trend_stock'),
    path('addtrend',views.addtrend, name='addtrend'),
    path('trend2',views.trend2, name='trend2'),
    ] 

stock_project/choose/forms.py
from django import forms

class efgh(forms.Form):
    stock = forms.CharField(label='',widget=forms.TextInput(attrs={'type':'text','placeholder':'股票代碼/名稱'}))
    start_time = forms.CharField(label='開始時間:',widget=forms.TextInput(attrs={'type':'date','placeholder':'開始時間'}))
    end_time = forms.CharField(label='結束時間:',widget=forms.TextInput(attrs={'type':'date','placeholder':'結束時間'}))

stock_project/choose/views.py
from django.shortcuts import render
from choose.forms import efgh
import plotly.express as px
import datetime 
import requests
import pandas
from bs4 import BeautifulSoup
from transformers import BertTokenizer, TFBertForSequenceClassification
from transformers import InputExample, InputFeatures
import tensorflow as tf
import os
import time
#下載新聞標題及內容到電腦磁碟
from pandas_datareader import data as pdr
import numpy  as np
import plotly.graph_objs as go
import plotly.offline as opy
import pandas as pd
import math 
import twstock
#from talib import abstract #Ta-Lib分析套件
import random
import other      

def choose(request):
    url='https://tw.stock.yahoo.com/tw-market'
    list_req = requests.get(url)
    soup = BeautifulSoup(list_req.content, "html.parser")
    d=[]
    i=0
    f=0
    for a in soup.find_all('h3',{'class':'Mt(0) Mb(8px)'}):
        d.append([a.text,a.a.get('href')])
        i+=1
        if i == 10:
            break
    for b in soup.find_all('p',{'class':'Fz(16px) Lh(24px) LineClamp(2,48px) C($c-secondary-text) M(0)'}):
        d[f].append(b.text)
        f+=1
        if f == 10:
            break
    
    #大盤
    dtime = int(float(time.time())*1000)
    url = 'https://mis.twse.com.tw/stock/data/mis_ohlc_TSE.txt?_='+str(dtime)
    res = requests.get(url)
    jd = res.json()['ohlcArray']
    columns = ['c','s','ts','t']
    df = pd.DataFrame(jd, columns=columns)
    df.columns =['加權指數','成交金額','時間','日期']
    df['加權指數'] = pd.to_numeric(df['加權指數'])
    df['成交金額'] = df['成交金額'].astype(float)
    df['時間']=df['時間'].replace(np.nan,'133000')
    yesterday =res.json()['infoArray']
    df2=pd.DataFrame([yesterday[0]['y'], 0 , '0900' ,np.nan]).T
    #df.loc[0]=[yesterday[0]['y'], 0 , '0900' ,np.nan]
    df2.columns =df.columns
    df=pd.concat([df2,df],axis=0,ignore_index=True)
    allMoney=0
    for i in range(len(df['加權指數'])):#注意
            df['時間'][i]=df['時間'][i][0:2]+':'+df['時間'][i][2:4] 
            df['成交金額'][i]=df['成交金額'][i]/100 
            allMoney+=df['成交金額'][i]
            allMoney=round(allMoney,2)
    abc=str(df['加權指數'][len(df['加權指數'])-1])
    
    # trace1 = go.Bar(
    #     name='成交金額(億)',
    #     x=df['時間'],
    #     y=df['成交金額'],
    # )
    # trace2 = go.Scatter(
    #     name='加權指數',
    #     x=df['時間'],
    #     y=df['加權指數'],
    #     yaxis="y2"
    # )
    #
    # data = [trace1, trace2,]
    # layout = go.Layout(
    #     yaxis=dict(
    #         domain=[0, 0.5]
    #     ),
    #     legend=dict(
    #         traceorder="reversed"
    #     ),
    #     yaxis2=dict(
    #         domain=[0.5, 1]
    #     ),
    #     title='加權指數:'+abc,
    # )
    df['昨收價']=df['加權指數'][0]
    trace1 = go.Bar(
        name='成交金額(億)',
        x=df['時間'],
        y=df['成交金額'],
    
    )
    trace2 = go.Scatter(
        name='加權指數',
        x=df['時間'],
        y=df['加權指數'],
        yaxis="y2",
    )
    trace3 = go.Scatter(
        name='昨收',
        x=df['時間'],
        y=df['昨收價'],
        yaxis="y2",
    )
    
    data = [trace1,trace2,trace3]
    layout = go.Layout(
        yaxis=dict(
            domain=[0, 0.5]
        ),
        yaxis2=dict(
            domain=[0.5, 1]
        ),
        title='加權指數:'+abc,
    )
    fig =go.Figure(data=data, layout=layout)
    fig.update_xaxes(tick0='0900',dtick=5)
    fig.update_yaxes(exponentformat="none")
    fig.update_layout(hovermode="x unified",height=500)
    div = opy.plot(fig, auto_open=False, output_type='div')
    efg=float(abc)-float(df['加權指數'][0])
    hij=str(round((efg/float(abc)*100),2))
    stock_data=[]
    stock_data_2=[]
    stock_data.append(abc)
    stock_data.append('%.2f' %efg)
    stock_data.append(hij)
    stock_data_2.append(allMoney)
    return render(request,'choose/choose.html',{'d':d,'fig':div,'stock_data':stock_data,'stock_data_2':stock_data_2})
def timely_stock(request):
    get_text=request.GET.get("stock")
    request.session['stock']=get_text
    today = datetime.datetime.now() 
    nowtime=" 更新時間:" + today.strftime('%X')[0:5]
    #nowtime=" 更新時間:" + str(time.hour)+":"+str(time.minute)+'///'+str(time.time)
    have=other.sql(get_text)
    targets=have[0]
    stock_name=have[1]
    title_text=targets+' '+stock_name
    title=title_text
    time_tittle=nowtime
    #隨機推薦
    # stock = twstock.Stock('2330')  
    # bfp = twstock.BestFourPoint(stock)
    # target_price = stock.fetch_from(2022, 9)
    # name_attribute = ['Date', 'Capacity', 'Turnover', 'Open', 'high', 'low', 'close', 'Change', 'Transcation']
    # df1 = pd.DataFrame(columns  = name_attribute, data = target_price)
    #即時股價
    res = requests.get('https://tw.stock.yahoo.com/_td-stock/api/resource/FinanceChartService.ApacLibraCharts;autoRefresh=1653627795519;symbols=%5B%22'+targets+'.TW%22%5D;type=tick?bkt=&device=desktop&ecma=modern&feature=ecmaModern%2CuseVersionSwitch%2CuseNewQuoteTabColor&intl=tw&lang=zh-Hant-TW&partner=none&prid=a3olkn1h90moe&region=TW&site=finance&tz=Asia%2FTaipei&ver=1.2.1295&returnMeta=true')
    jd = res.json()['data']
    close = jd[0]['chart']['indicators']['quote'][0]['close']
    volume = jd[0]['chart']['indicators']['quote'][0]['volume']
    timestamp = jd[0]['chart']['timestamp']
    df = pandas.DataFrame({'timestamp':timestamp, '價':close, 'volume':volume,},)
    df['日期']=(pandas.to_datetime(df['timestamp'] + 3600 * 8, unit='s'))
    df['日期']=pandas.to_datetime(df['日期'],format ='%Y-%m-%d%H:%M')
    df['時間']=df['日期'].dt.strftime("%H:%M")
    
    fig = px.line(df,x='時間',y ='價',line_shape='linear',hover_data={'量':df.volume},width=1000)
    fig.update_xaxes(title_text='時間')
    fig.update_yaxes(title_text='價格')
    fig.update_layout(hovermode="x")
    fig.update_traces(connectgaps=True)
    #newfig="<div>"+fig.to_html()+"</div>"
    
    res = requests.get('https://tw.stock.yahoo.com/_td-stock/api/resource/StockServices.stockList;autoRefresh=1653805943474;fields=avgPrice%2Corderbook;symbols='+targets+'.TW;version=v1?bkt=Test-P13N-author-V2&device=desktop&ecma=modern&feature=ecmaModern%2CuseVersionSwitch%2CuseNewQuoteTabColor%2CuseFinanceP13NStreamV2&intl=tw&lang=zh-Hant-TW&partner=none&prid=ago6ti1h964nt&region=TW&site=finance&tz=Asia%2FTaipei&ver=1.2.1295&returnMeta=true')
    jd = res.json()['data']
    
    one = jd[0]['orderbook'][0]
    two = jd[0]['orderbook'][1]
    three = jd[0]['orderbook'][2]
    four = jd[0]['orderbook'][3]
    five = jd[0]['orderbook'][4]
    
    cd = pandas.DataFrame({'one':one, 'two':two, 'three':three,'four':four,'five':five,},)
    cd =cd.T
    cd.columns=['委賣價','委賣量1','委買價','委買量1','委賣量','委買量']

    
    
    fig2 = px.bar(cd,
                 title="委買",
                 x="委買量",
                 y="委買價",
                 hover_data = ['委買量','委買價'],   # 懸停參數
                 width=250,
                 height=300,
                 orientation='h',
                )
    x_maxs = []
    for trace_data in fig2.data:
        x_maxs.append(max(trace_data.x))
    x_max = max(x_maxs)
    fig2.update_layout(yaxis={"mirror" : "allticks", 'side': 'right'},xaxis={'range': [1.05*x_max, 0], 'side': 'bottom'} ,title_text='委買',title_x=0.5 )
    
    #newfig+="<div>"+fig2.to_html()+"</div>"
    fig3 = px.bar(cd,
                 title="委賣",
                 x="委賣量",
                 y="委賣價",
                 hover_data = ['委賣量','委賣價'],   # 懸停參數
                 width=250,
                 height=300,
                 orientation='h',
                )
    fig3.update_layout(title_text='委賣', title_x=0.5)
    #newfig+="<div id='five'>"+"<div>"+fig2.to_html()+"</div>"+"<div>"+fig3.to_html()+"</div>"+"</div>"
    try:
        res = requests.get("https://mis.twse.com.tw/stock/api/getStockInfo.jsp?ex_ch=tse_"+targets+".tw&json=1&delay=0&_=1552123547443")
        data2 = res.json()['msgArray']
        # 過濾出有用到的欄位
        columns = ['c','n','z','tv','v','o','h','l','y']
        gh = pandas.DataFrame(data2, columns=columns)
        gh.columns = ['股票代號','公司簡稱','當盤成交價','當盤成交量','累積成交量','開盤價','最高價','最低價','昨收價']
        gh.insert(9, "漲跌百分比", 0.0) 
        gh.iloc[0, [5,6,7]] = gh.iloc[0, [5,6,7]].astype(float)
        # 新增漲跌百分比
        if gh['當盤成交價'].iloc[0] != "-":
            gh.iloc[0, [2,8]] = gh.iloc[0, [2,8]].astype(float)
            gh['漲跌百分比'].iloc[0] = round(((gh['當盤成交價'].iloc[0] - gh['昨收價'].iloc[0])/gh['昨收價'].iloc[0] * 100),2)
           
        #三大法人
        ef = pd.DataFrame()
        today = datetime.date.today()
        strToday=str(today)
        day = strToday[:4]+strToday[5:7]+strToday[8:]
        
        while True:
            url = 'https://www.twse.com.tw/fund/T86?response=json&date=' + day + '&selectType=ALL'
            res = requests.get(url)
            inv_json = res.json()
            if res.json()['stat'] == '很抱歉，沒有符合條件的資料!':
                end_time= str(today-datetime.timedelta(days=1))
                day= end_time[:4]+end_time[5:7]+end_time[8:]
            elif res.json()['stat'] == 'OK':
                ef_inv = pd.DataFrame.from_dict(inv_json['data'])
                ef_inv.insert(0, '日期', datetime.datetime(int(day[:4]), int(day[4:6]), int(day[6:])))
                ef = ef.append(ef_inv, ignore_index = True)
                break
        ef.columns = ['日期', '證券代號', '證券名稱', '外陸資買進股數(不含外資自營商)', '外陸資賣出股數(不含外資自營商)', '外陸資買賣超股數(不含外資自營商)', '外資自營商買進股數', '外資自營商賣出股數', '外資自營商買賣超股數', '投信買進股數', '投信賣出股數', '投信買賣超股數', '自營商買賣超股數', '自營商買進股數(自行買賣)', '自營商賣出股數(自行買賣)', '自營商買賣超股數(自行買賣)', '自營商買進股數(避險)', '自營商賣出股數(避險)', '自營商買賣超股數(避險)', '三大法人買賣超股數']
        ef=ef.drop(columns= ['外陸資買進股數(不含外資自營商)', '外陸資賣出股數(不含外資自營商)', '外資自營商買進股數', '外資自營商賣出股數', '外資自營商買賣超股數', '投信買進股數', '投信賣出股數', '自營商買進股數(自行買賣)', '自營商賣出股數(自行買賣)', '自營商買賣超股數(自行買賣)', '自營商買進股數(避險)', '自營商賣出股數(避險)', '自營商買賣超股數(避險)', '三大法人買賣超股數'])
        
        # 加入股票代碼篩選
        if targets == None:
            pass

stock_project/choose/templates/choose/addrandom.html
<div>{{suggest}} <input type='submit' id='addrandom' value='送出'></div>

stock_project/choose/templates/choose/asd.html
<p id='choose_title'   data-aos="fade-right" >{{title}}<span>{{time}}</span></p>
{% autoescape off %}
	{{newfig}}
{% endautoescape %}
<br>
<table class='fig' id='news_table'>
	<tr> 
		<th>Yahoo新聞標題<span>(使用yahoo股市的新聞網址，判斷新聞的好壞評級)</span></th>
		<th>預測評級<span>(非常好-好-普通-不好-非常不好)</span></th>
	</tr>
	{%for i in newData %}
	<tr>
		<td> <a href='{{i.3}}' target='_blank'>{{i.0}}</a> </td>
		<td> {{i.4}} </td>
	</tr>
	{% endfor %}
</table>
<!-- {{a1}} -->

stock_project/choose/templates/choose/choose.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>個股看盤</title>
    <link rel="stylesheet" href="{% static 'stock/css/new.css' %}">
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
</head>
<body>
    <div class="top"   data-aos="fade-down" data-aos-anchor-placement="top-bottom">
		<header  data-aos="fade-right" data-aos-offset="300" data-aos-easing="ease-in-sine">
            <div><img src="/static/stock/img/logo.png" alt="logo"></div>
			<p>朝陽虛擬智選股</p>
		</header>
		<nav>
			<ul id="nav"  data-aos="fade-down" data-aos-easing="linear" data-aos-duration="1500">
				<li><a href="{% url 'stock:stock' %}">首頁</a></li>
				<li id="foo">個股看盤</li>
				<li><a href="{% url 'chips:chips' %}">籌碼排序</a></li>
				<li><a href="{% url 'trend:trend' %}">多圖走勢</a></li>
				<li><a href="{% url 'newbie:newbie' %}">新手教學</a></li>
				<li><a href="{% url 'transaction:transaction' %}">虛擬交易</a></li>
				<li><a href="{% url 'predict:predict' %}">股票預測</a></li>
            </ul>
		</nav>
	</div>
	<div id="main">
		<div id='qr_div'  data-aos="fade-right" data-aos-easing="ease-in-sine">
			<div id="qr_code">
				<a href="https://lin.ee/YFR4wbS" target="_blank"><img src="https://scdn.line-apps.com/n/line_add_friends/btn/zh-Hant.png" alt="加入好友"></a>
				<img src="/static/stock/img/906csrwq.png" alt="">
			</div>
			<p>官方Line bot帳號<br>可隨時查詢股票資訊</p>
		</div>
		<div id="status"><img src="/static/stock/img/Spin-1s-200px.gif"/></div>
		<div id='choosepage_div'  data-aos="fade-right" >
			<div id='page'>
				<p>即時股價</p>
				<h1><a href="{%url 'choose:choose2' %}">技術線圖</a></h1>
			</div>
			<div id='choose_random'>
				<div id='choose_div'>
					<input id='s_num' type='text' placeholder='股票代碼/名稱'>
				   	<input id='submit' type="submit" value="送出">
			   	</div>
			</div>
		</div>
		<div id='choo'  data-aos="fade-right" >
			<div id='homepage_left'>
				<table id='market_table'>
					<tr>
						<th colspan="3">加權指數</th>
						<th>成交金額(億)</th>
					</tr>
					<tr>
					{% for i in stock_data %}
						<td>{{i}}</td>
					{% endfor %}
					{% for i in stock_data_2 %}
						<td>{{i}}</td>
					{% endfor %}
					</tr>
				</table>
				{% autoescape off %}
					{{fig}}
				{% endautoescape %}
			</div>
			<div id="homepage_right">
				<div id="new">
					<h1>熱門新聞</h1><br>
					{%for i in d %}
						<div id="new_div">
							<a href={{i.1}} target='_blank'>{{i.0}}</a>
							<div class="wrap">
			  					<div class="cont">
									<p class="txt">{{i.2}}</p>
								</div>
							</div>
						</div>
					{%endfor%}
				</div>
			</div>
		</div>
   	</div>
	<footer  data-aos="fade-up" data-aos-anchor-placement="top-bottom">
		<table   data-aos="fade-right" data-aos-easing="ease-in-sine">
			<thead>
				<tr>
					<th>開發團隊</th>
				</tr>
			</thead>
			<tbody>
				<tr><td>指導老師	陳榮靜</td></tr>
				<tr><td>10814056	柯沛淳</td></tr>
				<tr><td>10814071	溫聖倫</td></tr>
				<tr><td>10814090	林廷逸</td></tr>
				<tr><td>10814092	游凱翔</td></tr>
				<tr><td>10814137	方佳琪</td></tr>
				<tr><td>10814160	伍慶翎</td></tr>			
			</tbody>
		</table>
		<table   data-aos="fade-right" data-aos-easing="ease-in-sine">
			<thead> 
				<tr>
					<th>系統環境</th>
				</tr>
			</thead>
			<tbody>
				<tr><td>PostgreSQL</td></tr>
				<tr><td>Python</td></tr>
				<tr><td>Django</td></tr>
				<tr><td>Excel</td></tr>
				<tr><td>HTML5</td></tr>
				<tr><td>CSS</td></tr>
				<tr><td>Bootstrap</td></tr>
				<tr><td>JavaScript</td></tr>
				<tr><td>jQuery</td></tr>
				<tr><td>AJAX</td></tr>
			</tbody>
		</table>
		<table  data-aos="fade-right" data-aos-easing="ease-in-sine">
			<thead>
				<tr>
					<th>資料來源</th>
				</tr>
			</thead>
			<tbody>
				<tr><td><a href='https://tw.stock.yahoo.com/' target="_blank">Yahoo股市</a></td></tr>
				<tr><td><a href='https://goodinfo.tw/tw/index.asp' target="_blank">Goodinfo</a></td></tr>
				<tr><td><a href='https://www.twse.com.tw/zh/' target="_blank">台灣證券交易所</a></td></tr>
				<tr><td><a href='https://histock.tw/' target="_blank">histock</a></td></tr>
			</tbody>
		</table>
		<table  data-aos="fade-right" data-aos-easing="ease-in-sine">
			<thead> 
				<tr>
					<th>主要應用</th>
				</tr>
			</thead>
			<tbody>
				<tr><td>LSTM</td></tr>
				<tr><td>BERT</td></tr>
			</tbody>
		</table>
	</footer>
	<script>
		AOS.init({
			duration:500,
		});
	</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script> 
<script src="{% static 'stock/js/all.js' %}" type="text/javascript"></script>
<script> 
		var i=$('#market_table tbody tr td:eq(2)').text()
		if (Number($('#market_table tbody tr td:eq(2)').text())>0){
			   $('#market_table tbody tr td:eq(2)').attr('class','red');
			   $('#market_table tbody tr td:eq(2)').append('%');
		  }
		else if(Number($('#market_table tbody tr td:eq(2)').text())<0){
			$('#market_table tbody tr td:eq(2)').attr('class','green');
			$('#market_table tbody tr td:eq(2)').append('%');
			}
		else if(Number($('#market_table tbody tr td:eq(2)').text())==0){
			$('#market_table tbody tr td:eq(2)').attr('class','white');
			$('#market_table tbody tr td:eq(2)').append('%');
			}
		
		var j=$('#market_table tbody tr td:eq(1)').text()
		if (Number($('#market_table tbody tr td:eq(1)').text())>0){
			   $('#market_table tbody tr td:eq(1)').attr('class','red');
		  }
		else if(Number($('#market_table tbody tr td:eq(1)').text())<0){
			$('#market_table tbody tr td:eq(1)').attr('class','green');
			}
		else if(Number($('#market_table tbody tr td:eq(1)').text())==0){
			$('#market_table tbody tr td:eq(1)').attr('class','white');
			}
		$('#hot  tbody tr td:nth-child(4)').each(function(){
			if($(this).text()>0){
				$(this).addClass("red");
			}
			else if($(this).text()<0){
				$(this).addClass("green");
			}
			else{
				$(this).addClass("white");
			}
		})
		$('#hot  tbody tr td:nth-child(5)').each(function(){
			if($(this).text().replace('%', '')>0){
				$(this).addClass("red");
			}
			else if($(this).text().replace('%', '')<0){
				$(this).addClass("green");
			}
			else{
				$(this).addClass("white");
			}
		})
	</script>	
</body>
</html>