stock_project/chips/urls.py
from django.urls import path
from chips import views

app_name='chips'
urlpatterns=[
    path('',views.chips, name='chips'),
    path('chips2',views.chips2, name='chips2'),
    ] 

stock_project/choose/urls.py
from django.urls import path
from choose import views

app_name='choose'
urlpatterns=[
    path('',views.choose, name='choose'),
    path('timely_stock',views.timely_stock, name='timely_stock'),
    path('choose2',views.choose2, name='choose2'),
    path('choose2_submit',views.choose2_submit, name='choose2_submit'),
    #path('addrandom',views.addrandom, name='addrandom'),
    #path('random',views.random, name='random'),
    ] 

stock_project/newbie/urls.py
from django.urls import path
from newbie import views

app_name='newbie'
urlpatterns=[
    path('',views.newbie, name='newbie'),
    ] 

stock_project/stock/urls.py
from django.urls import path
from stock import views

app_name='stock'
urlpatterns=[
    path('',views.stock, name='stock'),
    ] 

stock_project/stock_project/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from stock import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('stock/',include('stock.urls',namespace='stock')),
    path('choose/',include('choose.urls',namespace='choose')),
    path('chips/',include('chips.urls',namespace='chips')),
    path('trend/',include('trend.urls',namespace='trend')),
    path('newbie/',include('newbie.urls',namespace='newbie')),
    path('transaction/',include('transaction.urls',namespace='transaction')),
    path('predict/',include('predict.urls',namespace='predict')),
    re_path('.*',views.stock),
    ]

stock_project/transaction/urls.py
from django.urls import path
from transaction import views

app_name='transaction'
urlpatterns = [
    path('', views.transaction, name='transaction'),
    path('login_register/', views.login_register,name='login_register'),
    path('btn1Create/', views.btn1Create,name='btn1Create'),
    path('btn2Create/', views.btn2Create,name='btn2Create'),
    path('btn3Create', views.btn3Create,name='btn3Create'),
    path('btn4Create/', views.btn4Create,name='btn4Create'),
    path('btn5Create/', views.btn5Create,name='btn5Create'),
    path('btn1Create/clickbuy1', views.clickbuy1,name='clickbuy1'),
    path('btn1Create/buy_sell', views.buy_sell,name='buy_sell'),
    path('logout', views.logout,name='logout'),
]


stock_project/trend/urls.py
from django.urls import path
from trend import views

app_name='trend'
urlpatterns=[
    path('',views.trend, name='trend'),
    # path('trend_stock',views.trend_stock, name='trend_stock'),
    path('addtrend',views.addtrend, name='addtrend'),
    path('trend2',views.trend2, name='trend2'),
    ] 

stock_project/transaction/models.py
from django.db import models

# Create your models here.

stock_project/transaction/forms.py
from django import forms


class login_forms(forms.Form):
    id = forms.EmailField(label='',widget=forms.EmailInput(attrs={'placeholder': 'E-mail'}))
    password = forms.CharField(label='',widget=forms.PasswordInput(attrs={'placeholder':'密碼'}))
    
class clickbuy(forms.Form):
    stock_id = forms.CharField(label='',widget=forms.TextInput(attrs={'placeholder':'股票代碼/名稱'}))
    def set(self,val):
        self.fields['stock_id'].widget.attrs.update({'value': val})

class sent(forms.Form):
    choose = forms.ChoiceField(label='買/賣', widget=forms.RadioSelect(attrs={'id':'radio'}),choices=(('buy', '買'),('sell', '賣')),)
    count = forms.CharField(label='數量',widget=forms.TextInput(attrs={'placeholder':'張數'}))

stock_project/transaction/views.py
from django.shortcuts import render,redirect
from transaction.forms import sent,login_forms,clickbuy
from django.contrib import messages
import twstock
import other
from django.db import connection
from _ast import If

#django session
#https://iter01.com/672416.html 
#https://ithelp.ithome.com.tw/m/articles/10212461

def transaction(request):
    if 'saveid' in request.session:
        return redirect('transaction:btn1Create')
    return render(request,'transaction/transaction.html',{'who_login':login_forms()})
    
def login_register(request):
    if request.POST:
        if 'login' in request.POST:
            idVal = request.POST["id"]
            passwordVal = request.POST["password"]
            
            with connection.cursor() as cursor:
                # 查詢資料SQL語法
                command = "SELECT * FROM charts where id=%s "
                cursor.execute(command,[idVal])
                result = cursor.fetchone()
                if result is None:
                    messages.success(request,'尚未註冊')
                    return redirect('transaction:transaction')
                else:
                    var1 = idVal
                    var11=result[0]
                    var2 = passwordVal
                    var22=result[1]
                    if (var1) ==(var11) and (var2) == (var22):
                        request.session['saveid']=var1
                        messages.success(request,idVal+'，登入成功')
                        #return render(request,'transaction/transaction2.html',{'id':idVal})
                        return redirect('transaction:btn1Create')
                    else:
                        messages.success(request,'帳號或密碼錯誤')
                        return redirect('transaction:transaction')
        else:
            idVal = request.POST["id"]
            passwordVal = request.POST["password"]
            
            try:
                with connection.cursor() as cursor:
                    command = "INSERT INTO charts(id,password,allmoney)VALUES(%s, %s, 10000000)"
                    cursor.execute(command,[idVal,passwordVal])
                    connection.commit()#回傳結果到另一個頁面  
                messages.success(request,idVal+'註冊成功')
                return redirect('transaction:transaction')
            except:
                with connection.cursor() as cursor:
                    # 查詢資料SQL語法
                    command = "SELECT * FROM charts where id=%s "
                    cursor.execute(command,[idVal])
                    result = cursor.fetchone()
                messages.success(request,idVal+'，帳號已註冊，請直接登入')
                return redirect('transaction:transaction')
    else:
        messages.success(request,'尚未登入')
        return redirect('transaction:transaction')     
        
def btn1Create(request):
     return render(request, 'transaction/btn1Create.html',{'who':sent(),'stock_num':clickbuy(),'id':request.session['saveid']})
def clickbuy1(request):#查詢
    try:
        get_text = request.GET["stock_id"]
        have=other.sql(get_text)
        stockid=have[0]
        stock_name=have[1]
        title_text=stockid+' '+stock_name
        stock=twstock.realtime.get(stockid)
        best_bid_price=stock['realtime']['best_bid_price']
        best_bid_price=[round(float(i),3) for i in best_bid_price]
        best_ask_price=stock['realtime']['best_ask_price']
        best_ask_price=[round(float(i),3) for i in best_ask_price]
        all_price=zip(best_bid_price,best_ask_price)
        newform = clickbuy()
        newform.set(get_text)
        request.session['ask']=best_ask_price[0]
        request.session['have0']=stockid
    except:
        messages.success(request,get_text+' 此股票代非上市股票')
        return redirect('transaction:btn1Create')
    return render(request, 'transaction/btn1Create.html',{'who':sent(),'stock_num':newform,'result':title_text,'result_price':all_price,'id':request.session['saveid'],'have':have,'best_ask_price':best_ask_price[0]})
def buy_sell(request):#查詢   
    try:    
        get_text = request.session['have0']
        have=other.sql(get_text)
        stockid=have[0]
        stock_name=have[1]
        title_text=stockid+' '+stock_name
        choose_buy_sell = request.GET["choose"]
        stock_price = str(request.session['ask'])
        buy_sell_count = request.GET["count"]
        saveid=request.session['saveid']
        stock=twstock.realtime.get(stockid) 
                  
        if choose_buy_sell   == 'buy' : #買進
            with connection.cursor() as cursor:
                #-------------------------------------------------
                command = "SELECT allmoney FROM charts WHERE id = %s"#判斷金額足夠
                cursor.execute(command,[saveid])
                result = cursor.fetchone()[0]
                if float(result) < float(stock_price)*1000*int(buy_sell_count):
                    buy_sell_result="金額不足無法買進"
                else:
                    #-------------------------------------------------
                    command = "SELECT * FROM stock ORDER BY id1 ASC " #抓取資料庫資料行數
                    cursor.execute(command)
                    result = cursor.fetchall()
                    print(result,"#判斷金額足夠玩，抓取資料庫資料行數")
                    if len(result) == 0 :
                        id1=1
                    else:
                        id1=result[-1][0]+1
                    #-------------------------------------------------
                                                    #抓取3種輸入資料 代碼 價格 張數
                    print("id1",id1,"抓取3種輸入資料 代碼 價格 張數")
                    command = "insert into stock(id1,stockmoney1,stockmoney2,stockmoney3,stock_id) values(%s,%s,%s,%s,%s)"
                    cursor.execute(command,[id1,stockid,stock_price,buy_sell_count,saveid])
                    
                    command = "SELECT * FROM record " #抓取資料庫資料行數
                    cursor.execute(command)
                    result = cursor.fetchall()
                    if len(result) == 0 :
                        id1=1
                    else:
                        id1=result[-1][0]+1 #-1:最後一筆資料\0:id1[]
                        
                    command = "insert into record(id1,stockmoney1,stockmoney2,stockmoney3,stock_id,date1,buy_sell) values(%s,%s,%s,%s,%s,now(),'買進')"
                    cursor.execute(command,[id1,stockid,stock_price,buy_sell_count,saveid])
                    
                    command = "SELECT * FROM record_1 " #抓取資料庫資料行數
                    cursor.execute(command)
                    result = cursor.fetchall()
                    if len(result) == 0 :
                        id1=1
                    else:
                        id1=len(result)+1
                    
                    command = "insert into record_1(id1,stockmoney1,stockmoney2,stockmoney3,stock_id,date1,buy_sell) values(%s,%s,%s,%s,%s,now(),'買進')"
                    cursor.execute(command,[id1,stockid,stock_price,buy_sell_count,saveid])
                    #------------------------------------------------- 修改原始金額
                    command = "SELECT allmoney FROM charts WHERE id = %s"    
                    cursor.execute(command,[saveid])
    
                    result1 = cursor.fetchone()
                    arr1 = float(stock_price)*1000*int(buy_sell_count)
                    result2 = float(result1[0]) - arr1
                    command = "UPDATE charts SET allmoney = %s WHERE id = %s"
                    cursor.execute(command,[result2, saveid])
    
                    #-------------------------------------------------
                    connection.commit() 
                    
                    buy_sell_result=("已買入 :  "+title_text+"    /價格為 : "+stock_price+'  /張數 : '+buy_sell_count+'張') #顯示買了甚麼
        #買進的底
        if choose_buy_sell == 'sell' :                                  #賣出
            with connection.cursor() as cursor:
                command = "SELECT stockmoney1 FROM stock where (stock_id=%s)and(stockmoney1=%s)"
                cursor.execute(command,[saveid,stockid])
                result = cursor.fetchall()       #result[0] 股票代碼
            print('result',result[0][0])
            
            with connection.cursor() as cursor:
                command = "SELECT sum(stockmoney3) FROM stock GROUP BY (stock_id=%s)and(stockmoney1=%s)"
                cursor.execute(command,[saveid,stockid])
                rrresult = cursor.fetchall()
            print('rrresult:',rrresult)
            if result[0][0] is None:
                buy_sell_result=('您並未擁有'+title_text+'股票')
            elif int(rrresult[-1][0]) < int(buy_sell_count):
                buy_sell_result=('您擁有的'+title_text+'只有'+str(rrresult[-1][0])+'張'+'，不足'+str(buy_sell_count)+'張')
                print('abc',int(rrresult[-1][0]) , int(buy_sell_count))
            
            else:
                print('123')
                if result[0][0] == stockid:
                    #connection.commit()    #connection.close()                     
                    with connection.cursor() as cursor: 
                        command = "SELECT sum(stockmoney3) FROM stock GROUP BY (stock_id=%s)and(stockmoney1=%s)" 
                        cursor.execute(command,[saveid,stockid])
                        result5 = cursor.fetchall()  #加總股票張數(庫存)
                        connection.commit()    
                    if int(buy_sell_count)<=int(result5[-1][0]):#如果賣出的張數<=庫存張數
                        
                        print(int(buy_sell_count),'  ',int(result5[-1][0]),'如果賣出的張數<=庫存張數')
                        
        
                        #抓原本資產 加上賺的 刪原本的股票 新增剩餘的股票
                        #connection.commit()    #connection.close()                     
                        with connection.cursor() as cursor: 

stock_project/transaction/templates/transaction/btn1Create.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>虛擬交易</title>
    <link rel="stylesheet" href="{% static 'stock/css/new.css' %}">
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
</head>
<body>
	{% if messages %}
		<script>
		    {% for msg in messages %}
		        alert('{{ msg.message }}');
		    {% endfor %}
		</script>
	{% endif %}
	<div class="top"   data-aos="fade-down" data-aos-anchor-placement="top-bottom">
		<header  data-aos="fade-right" data-aos-offset="300" data-aos-easing="ease-in-sine">
            <div><img src="/static/stock/img/logo.png" alt="logo"></div>
			<p>朝陽虛擬智選股</p>
		</header>
		<nav>
			<ul id="nav"  data-aos="fade-down" data-aos-easing="linear" data-aos-duration="1500">
				<li><a href="{% url 'stock:stock' %}">首頁</a></li>
				<li><a href="{% url 'choose:choose' %}">個股看盤</a></li>
				<li><a href="{% url 'chips:chips' %}">籌碼排序</a></li>
				<li><a href="{% url 'trend:trend' %}">多圖走勢</a></li>
				<li><a href="{% url 'newbie:newbie' %}">新手教學</a></li>
				<li  id="foo">虛擬交易</li>
				<li><a href="{% url 'predict:predict' %}">股票預測</a></li>
            </ul>
		</nav>
	</div>
	<div id="main">
		<div id='qr_div'  data-aos="fade-right" data-aos-easing="ease-in-sine">
			<div id="qr_code">
				<a href="https://lin.ee/YFR4wbS" target="_blank"><img src="https://scdn.line-apps.com/n/line_add_friends/btn/zh-Hant.png" alt="加入好友"></a>
				<img src="/static/stock/img/906csrwq.png" alt="">
			</div>
			<p>官方Line bot帳號<br>可隨時查詢股票資訊</p>
		</div>
		<div id='t1_div' data-aos="fade-right" data-aos-easing="ease-in-sine">
			<div id='transaction2'>
				<div id='t2_nav'>
					<p id='transaction2_btn'>快速下單</p>
					<p><a id='t2_nav_border-left' href="{%url 'transaction:btn2Create' %}">帳戶概覽</a></p>
					<p><a href="{%url 'transaction:btn3Create' %}">交易紀錄</a></p>
					<p><a href="{%url 'transaction:btn4Create' %}">庫存明細</a></p>
					<p><a href="{%url 'transaction:btn5Create' %}">損益計算</a></p>
				</div>
				<div id='id_box'>
					<div id='id_img'><img src="/static/stock/img/id_img.png" alt="people"></div>
					<p><span>{{id}}</span></p>
					<a id='logout' href="{%url 'transaction:logout' %}">登出</a>
				</div>
			</div>
			<div id='btn1'>
				<div id='btn1_div'  data-aos="flip-left"  data-aos-easing="ease-in-sine">
					<div class="wave2 one"></div>
				    <div class="wave2 two"></div>
				    <div class="wave2 three"></div>
					<p class='bt1_title'>STEP1 輸入股票代碼或名稱，查詢該股票的五檔價</p>
					<form id='aa' action="clickbuy1" method="get">
					{% csrf_token %}
					{{ stock_num.as_p }}
					<input id='search_img' type="submit" value='送出' onClick="document.formname.submit()">
					</form>
					<div id='btn1_forms1'>
						<p>{{result}}<p>
						{% if result_price %}
							<table>
								<tr>
									<th>委買</th>
									<th>委賣</th>
								</tr>
								{% for b,a in result_price %}
								<tr>
									<td> {{b}} </td>
									<td id='sell'> {{a}} </td>
								</tr>
								{% endfor %}
							</table>
						{% endif %}
					</div>
				</div>
				<div id='btn1_div2'   data-aos="flip-right" data-aos-easing="ease-in-sine">
					<div class="wave3 one"></div>
				    <div class="wave3 two"></div>
				    <div class="wave3 three"></div>
					<p class='bt1_title'>STEP2 選擇買/賣，送出後即可至交易紀錄查看。</p>
					<form id='bb' action="buy_sell" method="get">
						<h1>股票代碼 :<span>{{have.0}} {{have.1}}</span>價格 :<span>{{best_ask_price}}</span></h1>
						<div id='btn1_forms2'>
							{% csrf_token %}
							{{ who.as_p }}
							<input id='search_img' type="submit" value='送出' onClick="document.formname.submit()">
						</div>
					</form>		
					<p id='btn1_text'>{{buy_sell_result}}</p>
				</div>
			</div>
		</div>
	</div>	
	<footer  data-aos="fade-up" data-aos-anchor-placement="top-bottom">
		<table   data-aos="fade-right" data-aos-easing="ease-in-sine">
			<thead>
				<tr>
					<th>開發團隊</th>
				</tr>
			</thead>
			<tbody>
				<tr><td>指導老師	陳榮靜</td></tr>
				<tr><td>10814056	柯沛淳</td></tr>
				<tr><td>10814071	溫聖倫</td></tr>
				<tr><td>10814090	林廷逸</td></tr>
				<tr><td>10814092	游凱翔</td></tr>
				<tr><td>10814137	方佳琪</td></tr>
				<tr><td>10814160	伍慶翎</td></tr>			
			</tbody>
		</table>
		<table   data-aos="fade-right" data-aos-easing="ease-in-sine">
			<thead> 
				<tr>
					<th>系統環境</th>
				</tr>
			</thead>
			<tbody>
				<tr><td>PostgreSQL</td></tr>
				<tr><td>Python</td></tr>
				<tr><td>Django</td></tr>
				<tr><td>Excel</td></tr>
				<tr><td>HTML5</td></tr>
				<tr><td>CSS</td></tr>
				<tr><td>Bootstrap</td></tr>
				<tr><td>JavaScript</td></tr>
				<tr><td>jQuery</td></tr>
				<tr><td>AJAX</td></tr>
			</tbody>
		</table>
		<table  data-aos="fade-right" data-aos-easing="ease-in-sine">
			<thead>
				<tr>
					<th>資料來源</th>
				</tr>
			</thead>
			<tbody>
				<tr><td><a href='https://tw.stock.yahoo.com/' target="_blank">Yahoo股市</a></td></tr>
				<tr><td><a href='https://goodinfo.tw/tw/index.asp' target="_blank">Goodinfo</a></td></tr>
				<tr><td><a href='https://www.twse.com.tw/zh/' target="_blank">台灣證券交易所</a></td></tr>
				<tr><td><a href='https://histock.tw/' target="_blank">histock</a></td></tr>
			</tbody>
		</table>
		<table  data-aos="fade-right" data-aos-easing="ease-in-sine">
			<thead> 
				<tr>
					<th>主要應用</th>
				</tr>
			</thead>
			<tbody>
				<tr><td>LSTM</td></tr>
				<tr><td>BERT</td></tr>
			</tbody>
		</table>
	</footer>
	<script>
		AOS.init({
			duration:500,
		});
	</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script> 
<script src="{% static 'stock/js/all.js' %}" type="text/javascript"></script>	
</body>
</html>

stock_project/transaction/templates/transaction/transaction2.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>虛擬交易</title>
    <link rel="stylesheet" href="{% static 'stock/css/test.css' %}">
</head>
<body>
	{% if messages %}
		<script>
		    {% for msg in messages %}
		        alert('{{ msg.message }}');
		    {% endfor %}
		</script>
	{% endif %}
	<div class="top">
		<header>
            <div><img src="/static/stock/img/logo.png" alt="logo"></div>
			<p>朝陽虛擬智選股</p>
		</header>
		<nav>
			<ul class="nav">
				<li><a href="{% url 'stock:stock' %}">首頁</a></li>
				<li><a href="{% url 'markettrend:markettrend' %}">大盤走勢</a></li>
				<li><a href="{% url 'choose:choose' %}">個股看盤</a></li>
				<li><a href="{% url 'chips:chips' %}">籌碼排序</a></li>
				<li><a href="{% url 'trend:trend' %}">多圖走勢</a></li>
				<li><a href="{% url 'newbie:newbie' %}">新手教學</a></li>
				<li  id="foo">虛擬交易</li>
				<li><a href="{% url 'predict:predict' %}">股票預測</a></li>
			</ul>
		</nav>
	</div>
	<div id="main">
		<div id='transaction2'>
			<div id='id_box'>
				<div id='id_img'><img src="/static/stock/img/id_img.png" alt="people"></div>
				<p><span>{{id}}</span> 已登入</p>
				<a id='logout' href="{%url 'transaction:logout' %}">登出</a>
			</div>
			<p><a href="{%url 'transaction:btn1Create' %}">快速下單</a></p>
			<p><a href="{%url 'transaction:btn2Create' %}">帳戶概覽</a></p>
			<p><a href="{%url 'transaction:btn3Create' %}">交易紀錄</a></p>
			<p><a href="{%url 'transaction:btn4Create' %}">庫存明細</a></p>
			<p><a href="{%url 'transaction:btn5Create' %}">損益計算</a></p>
		</div>
	</div>
	<div id='qr_div' >
		<div id="qr_code">
			<a href="https://lin.ee/YFR4wbS" target="_blank"><img src="https://scdn.line-apps.com/n/line_add_friends/btn/zh-Hant.png" alt="加入好友"></a>
			<img src="/static/stock/img/906csrwq.png" alt="">
		</div>
		<p>官方Line bot帳號<br>可隨時查詢股票資訊</p>
	</div>
</body>
</html>